services:
  - type: web
    name: laravel-app
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --prefer-dist
      php artisan config:cache
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
